### ISSUE TITLE
Saving tokens results in "Something went wrong when trying to save credentials. Contact support."

### ISSUE THREAD

**Issue by ecammit** [skumail/Containerize-SuiteCloud-CLI#1]
Using this as the base test:

`docker run --entrypoint /bin/sh --rm -it -v .:/usr/src/app skumail/suitecloud-cli`

then execute:

`suitecloud account:savetoken --account "<my account>" --authid "<my name>" --tokenid "<my token>" --tokensecret "<my secret>"`

This results in: `Something went wrong when trying to save credentials. Contact support.`

This seems to be the solution: https://github.com/oracle/netsuite-suitecloud-sdk/issues/746#issuecomment-1683907712

The image needs the dbus package added and the `dbus-uuidgen --ensure` command run.

**Comment by ecammit** [comment]
Note that tagged version [1.6.0-alpine](https://hub.docker.com/layers/skumail/suitecloud-cli/1.6.0-alpine/images/sha256-75d8c5ff126a14bd74d54b066de7ca4a4b38cb7b29e2c754a9658f5ded547590?context=explore) is not affected by this bug.

**Comment by skumail** [comment]
@ecammit Thank you for taking the time to report this issue. Your contribution to the project is greatly appreciated.
